# Generated by Django 3.1 on 2020-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(help_text='地址', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(help_text='电子邮件', max_length=30),
        ),
    ]
